workflows:
  build:
    name: Build Dynamic Library
    max_build_duration: 60 # maximum build time in minutes
    environment:
      xcode: 'latest'
    scripts:
      - name: Checkout code
        script: |
          git clone https://github.com/ditcugithub/BIdbdj.git
          cd FloatingBrowser
      - name: Build dynamic library
        script: |
          mkdir -p build
          clang -dynamiclib -o build/libfloatingbrowser.dylib floating_browser.m -framework Cocoa -framework WebKit
    artifacts:
      - build/libfloatingbrowser.dylib
